<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Kelompok extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        $kelompok = [
            ['id' => 1, 'nama' => 'CIVIL E. 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'nama' => 'CIVIL E. 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'nama' => 'CIVIL E. 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'nama' => 'CIVIL E. 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'nama' => 'ARCHI 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'nama' => 'ARCHI 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 7, 'nama' => 'ARCHI 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8, 'nama' => 'ARCHI 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 9, 'nama' => 'ARCHI 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 10, 'nama' => 'ARCHI 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 11, 'nama' => 'EE-IOT 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 12, 'nama' => 'EE-IOT 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 13, 'nama' => 'AUTO-SMED 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 14, 'nama' => 'AUTO-SMED 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 15, 'nama' => 'AUTO-SMED 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 16, 'nama' => 'IE-GSLC 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 17, 'nama' => 'IE-GSLC 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 18, 'nama' => 'IE-GSLC 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 19, 'nama' => 'IE-GSLC 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 20, 'nama' => 'INFOR-SIB-DSA 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 21, 'nama' => 'INFOR-SIB-DSA 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 22, 'nama' => 'INFOR-SIB-DSA 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 23, 'nama' => 'INFOR-SIB-DSA 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 24, 'nama' => 'INFOR-SIB-DSA 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 25, 'nama' => 'INFOR-SIB-DSA 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 26, 'nama' => 'INFOR-SIB-DSA 7', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 27, 'nama' => 'INFOR-SIB-DSA 8', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 28, 'nama' => 'INFOR-SIB-DSA 9', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 29, 'nama' => 'INFOR-SIB-DSA 10', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 30, 'nama' => 'INFOR-SIB-DSA 11', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 31, 'nama' => 'INFOR-SIB-DSA 12', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 32, 'nama' => 'INFOR-SIB-DSA 13', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 33, 'nama' => 'INFOR-SIB-DSA 14', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 34, 'nama' => 'INFOR-SIB-DSA 15', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 35, 'nama' => 'INFOR-SIB-DSA 16', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 36, 'nama' => 'INFOR-SIB-DSA 17', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 37, 'nama' => 'INFOR-SIB-DSA 18', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 38, 'nama' => 'BUS-ACC 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 39, 'nama' => 'BUS-ACC 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 40, 'nama' => 'BUS-ACC 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 41, 'nama' => 'BUS-ACC 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 42, 'nama' => 'TAX-ACC 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 43, 'nama' => 'TAX-ACC 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 44, 'nama' => 'TAX-ACC 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 45, 'nama' => 'TAX-ACC 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 46, 'nama' => 'TAX-ACC 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 47, 'nama' => 'TAX-ACC 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 48, 'nama' => 'BUSINESS 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 49, 'nama' => 'BUSINESS 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 50, 'nama' => 'BUSINESS 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 51, 'nama' => 'BUSINESS 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 52, 'nama' => 'BUSINESS 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 53, 'nama' => 'BUSINESS 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 54, 'nama' => 'BUSINESS 7', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 55, 'nama' => 'BUSINESS 8', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 56, 'nama' => 'BUSINESS 9', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 57, 'nama' => 'BUSINESS 10', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 58, 'nama' => 'BUSINESS 11', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 59, 'nama' => 'BUSINESS 12', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 60, 'nama' => 'BUSINESS 13', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 61, 'nama' => 'BUSINESS 14', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 62, 'nama' => 'BUSINESS 15', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 63, 'nama' => 'HOTEL 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 64, 'nama' => 'HOTEL 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 65, 'nama' => 'HOTEL 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 66, 'nama' => 'HOTEL 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 67, 'nama' => 'C. TOURISM 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 68, 'nama' => 'MARKETING 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 69, 'nama' => 'MARKETING 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 70, 'nama' => 'MARKETING 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 71, 'nama' => 'FINEST 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 72, 'nama' => 'FINEST 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 73, 'nama' => 'FINEST 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 74, 'nama' => 'FINEST 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 75, 'nama' => 'FINEST 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 76, 'nama' => 'FINEST 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 77, 'nama' => 'PGPAUD 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 78, 'nama' => 'PGPAUD 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 79, 'nama' => 'PGSD 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 80, 'nama' => 'PGSD 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 81, 'nama' => 'PGSD 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 82, 'nama' => 'EB 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 83, 'nama' => 'ECI 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 84, 'nama' => 'ECI 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 85, 'nama' => 'CHINESE 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 86, 'nama' => 'CHINESE 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 87, 'nama' => 'CHINESE 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 88, 'nama' => 'IDS-IPD 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 89, 'nama' => 'IDS-IPD 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 90, 'nama' => 'IDS-IPD 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 91, 'nama' => 'IDS-IPD 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 92, 'nama' => 'IDS-IPD 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 93, 'nama' => 'IDS-IPD 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 94, 'nama' => 'VISUAL COM. 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 95, 'nama' => 'VISUAL COM. 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 96, 'nama' => 'VISUAL COM. 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 97, 'nama' => 'VISUAL COM. 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 98, 'nama' => 'VISUAL COM. 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 99, 'nama' => 'VISUAL COM. 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 100, 'nama' => 'VISUAL COM. 7', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 101, 'nama' => 'VISUAL COM. 8', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 102, 'nama' => 'VISUAL COM. 9', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 103, 'nama' => 'VISUAL COM. 10', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 104, 'nama' => 'VISUAL COM. 11', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 105, 'nama' => 'VISUAL COM. 12', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 106, 'nama' => 'VISUAL COM. 13', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 107, 'nama' => 'VISUAL COM. 14', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 108, 'nama' => 'FASHION 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 109, 'nama' => 'FASHION 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 110, 'nama' => 'SC-BJ 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 111, 'nama' => 'SC-BJ 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 112, 'nama' => 'SC-BJ 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 113, 'nama' => 'SC-BJ 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 114, 'nama' => 'SC-BJ 5', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 115, 'nama' => 'SC-BJ 6', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 116, 'nama' => 'SC-BJ 7', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 117, 'nama' => 'SC-BJ 8', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 118, 'nama' => 'IBE 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 119, 'nama' => 'IPDM 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 120, 'nama' => 'IPDM 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 121, 'nama' => 'IBM 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 122, 'nama' => 'IBM 2', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 123, 'nama' => 'IBM 3', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 124, 'nama' => 'IBM 4', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 125, 'nama' => 'IBACC 1', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 126, 'nama' => 'Kelompok Ncik', 'created_at' => $now, 'updated_at' => $now],
        ];

        $this->db->table('kelompok')->insertBatch($kelompok);
    }
}
