<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Ruangan extends Seeder
{
    public function run()
    {
        $ruangan = [
            ['ruangan' => 'P.202'],
            ['ruangan' => 'P.203'],
            ['ruangan' => 'P.204'],
            ['ruangan' => 'P.433'],
            ['ruangan' => 'P.501'],
            ['ruangan' => 'P.502'],
            ['ruangan' => 'P.502A'],
            ['ruangan' => 'P.503'],
            ['ruangan' => 'P.503A'],
            ['ruangan' => 'P.504'],
            ['ruangan' => 'P.505'],
            ['ruangan' => 'P.611'],
            ['ruangan' => 'P.612'],
            ['ruangan' => 'P.613'],
            ['ruangan' => 'P.614'],
            ['ruangan' => 'P.615'],
            ['ruangan' => 'P.617'],
            ['ruangan' => 'P.626'],
            ['ruangan' => 'P.701'],
            ['ruangan' => 'P.703'],
            ['ruangan' => 'P.705'],
            ['ruangan' => 'P.706'],
            ['ruangan' => 'P.707'],
            ['ruangan' => 'P.708'],
            ['ruangan' => 'P.709'],
            ['ruangan' => 'P.710'],
            ['ruangan' => 'P.802'],
            ['ruangan' => 'P.803'],
            ['ruangan' => 'P.804'],
            ['ruangan' => 'P.10.10'],
            ['ruangan' => 'Q.301'],
            ['ruangan' => 'Q.302'],
            ['ruangan' => 'Q.303'],
            ['ruangan' => 'Q.307'],
            ['ruangan' => 'Q.04.01'],
            ['ruangan' => 'Q.04.02A'],
            ['ruangan' => 'Q.04.02B'],
            ['ruangan' => 'Q.04.03A'],
            ['ruangan' => 'Q.04.03B'],
            ['ruangan' => 'Q.04.04'],
            ['ruangan' => 'Q.04.05'],
            ['ruangan' => 'Q.04.06A'],
            ['ruangan' => 'Q.04.06B'],
            ['ruangan' => 'Q.04.07'],
            ['ruangan' => 'Q.04.08A'],
            ['ruangan' => 'Q.04.08B'],
            ['ruangan' => 'Q.04.09'],
            ['ruangan' => 'Q.04.10'],
            ['ruangan' => 'Q.04.11'],
            ['ruangan' => 'Q.04.12'],
            ['ruangan' => 'Q.06.01'],
            ['ruangan' => 'Q.703'],
            ['ruangan' => 'Q.07.04'],
            ['ruangan' => 'Q.07.05'],
            ['ruangan' => 'Q.706'],
            ['ruangan' => 'Q.707'],
            ['ruangan' => 'Q.08.09A'],
            ['ruangan' => 'Q.08.09B'],
            ['ruangan' => 'Q.09.05'],
            ['ruangan' => 'Q.09.07B'],
            ['ruangan' => 'Amphitheater Q'],
            ['ruangan' => 'Auditorium Q'],
            ['ruangan' => 'Q.10.01'],
            ['ruangan' => 'Q.10.02'],
            ['ruangan' => 'Q.10.03'],
            ['ruangan' => 'Q.10.04'],
            ['ruangan' => 'Q.11.01'],
            ['ruangan' => 'Q.11.02'],
            ['ruangan' => 'T.212A'],
            ['ruangan' => 'T.212B'],
            ['ruangan' => 'T.213'],
            ['ruangan' => 'T.308'],
            ['ruangan' => 'T.313'],
            ['ruangan' => 'T.314'],
            ['ruangan' => 'T.316'],
            ['ruangan' => 'T.317'],
            ['ruangan' => 'T.318'],
            ['ruangan' => 'T.319'],
            ['ruangan' => 'T.320'],
            ['ruangan' => 'T.321'],
            ['ruangan' => 'T.322'],
            ['ruangan' => 'T.324'],
            ['ruangan' => 'T.325'],
            ['ruangan' => 'T.326'],
            ['ruangan' => 'T.415'],
            ['ruangan' => 'T.430'],
            ['ruangan' => 'T.418'],
            ['ruangan' => 'T.501'],
            ['ruangan' => 'T.502'],
            ['ruangan' => 'T.503'],
            ['ruangan' => 'T.516'],
            ['ruangan' => 'W.302'],
            ['ruangan' => 'W.303'],
            ['ruangan' => 'Auditorium W'],
            ['ruangan' => 'T.315'],            
        ];
        $this->db->table('ruangan')->insertBatch($ruangan);
    }
}
